### ISSUE TITLE
neonDataStackR still broken -- table_types not found

### ISSUE THREAD

**Issue by sokole** [NEONScience/NEON-utilities#13]
@chrlaney  sorry to be a pain! 

The package installs, but doesn't stack. Here I am trying to stack ticks sampled by drag cloths for D01, which has worked in the past. I also tried chem root and phys soil dist.

```
> neonDataStackR::stackByTable("NEON_count-ticks.zip")
Unpacked  NEON.D01.BART.DP1.10093.001.2014-05.basic.20170628T231809Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2014-06.basic.20170628T231831Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2014-07.basic.20170628T231900Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2014-08.basic.20170628T231928Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2014-09.basic.20170628T232034Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2014-10.basic.20170628T232059Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2015-05.basic.20170628T232205Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2015-06.basic.20170628T232219Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2015-07.basic.20170628T232239Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2015-08.basic.20170628T232301Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2015-09.basic.20170628T232325Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2016-05.basic.20170621T170108Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2016-06.basic.20170621T170208Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2016-07.basic.20170621T170304Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2016-08.basic.20170621T170403Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2016-09.basic.20170621T170504Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2016-10.basic.20170621T170606Z.zip
Unpacked  NEON.D01.BART.DP1.10093.001.2016-11.basic.20170621T170702Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2014-05.basic.20170628T231801Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2014-06.basic.20170628T231817Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2014-07.basic.20170628T231840Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2014-08.basic.20170628T231902Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2014-09.basic.20170628T231920Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2014-10.basic.20170628T231938Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2015-05.basic.20170628T232135Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2015-06.basic.20170628T232206Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2015-07.basic.20170628T232235Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2015-08.basic.20170628T232314Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2015-09.basic.20170628T232353Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-04.basic.20170621T170036Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-05.basic.20170621T170126Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-06.basic.20170621T170223Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-07.basic.20170621T170322Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-08.basic.20170621T170420Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-09.basic.20170621T170522Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-10.basic.20170621T170620Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2016-11.basic.20170621T170721Z.zip
Unpacked  NEON.D01.HARV.DP1.10093.001.2017-04.basic.20170621T170950Z.zip
Error in stackDataFiles(location.data) : object 'table_types' not found
```

**Comment by chrlaney** [comment]
Argh. I just used it on the same data product and it ran fine. Sorry! I wonder if I have to have table_types loaded into the environment before saving.

**Comment by chrlaney** [comment]
Just made a new commit. Try again @sokole? If not, any recommendations?

**Comment by sokole** [comment]
well, this doesn't work:
```
neonDataStackR::stackByTable("NEON_count-ticks.zip")
```
...but, this does work:
```
table_types <- neonDataStackR::table_types
neonDataStackR::stackByTable("NEON_count-ticks.zip")
```
So you're right. It's looking for the table_types in the global environment. If I put them there, it works fine.

**Comment by chrlaney** [comment]
Hmm, that helps. So I updated the code a little. Try again?

**Comment by sokole** [comment]
nope, still not found. 

It's probably not idea, but did you try a global assign from within your package?
```
table_types <<- table_types
```

**Comment by chrlaney** [comment]
No, but that's a good idea, as is an explicit call (maybe?) to load the data. Thanks for being the guinea pig, as I'm clearly having problems testing this in my local environment.

**Comment by sokole** [comment]
ah, you know what. I guess my problem is I'm not loading the package. I'm just doing the following:
```
neonDataStackR::stackByTable("NEON_phys-soil-distrib-periodic.zip")
```

When I do this it works fine...
```
library(neonDataStackR)
stackByTable('NEON_phys-soil-distrib-periodic.zip')
```

**Comment by sokole** [comment]
but yeah, I think if you are assuming table_types is in the environment in a function, you should put it there first.

**Comment by sokole** [comment]
or, where ever it is that you use table_types, probably the most fool-proof way of doing it is replacing table_types with neonDataStackR::table_types.

**Comment by chrlaney** [comment]
Thanks. I assumed with using Roxygen that the data would automatically be loaded, but that was not correct. Can I close this now?

**Comment by sokole** [comment]
sure

**Comment by kcawley** [comment]
@sokole @chrlaney I am having a similar problem when running the dissolved gas package. Should I be adding library(neonDataStackR) to the functions within the packages even though they have @importFrom neonDataStackR in the roxygen header and Imports: neonDataStackR in the DESCRIPTION file?

**Comment by chrlaney** [comment]
@kcawley Have you installed the most recent version of neonDataStackR?

**Comment by kcawley** [comment]
I guess not, I reinstalled (had to set force = T) and it appears to be working.

**Comment by chrlaney** [comment]
It's being updated quite often these days, so continue to use force = T.
